#!/bin/bash
set -e

./node_modules/.bin/styl -w < stylesheets/main.styl > stylesheets/main.css

./node_modules/.bin/hamlet -d templates

mkdir -p dist/templates
mv templates/*.js dist/templates

./node_modules/.bin/coffee -o dist -c source

echo "browserifying..."

./node_modules/.bin/browserify \
  dist/main.js \
  --standalone Sheet \
  -o dist/standalone.js

echo "done!"
